#!/usr/bin/env python3

# Copyright (c) 2019, G.A. vd. Hoorn
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author G.A. vd. Hoorn

# yes: this is all duplicated in the 'start_robot_state' script

import argparse
import socket
import struct
import time

J519_DEFAULT_PORT=60015
J519_VERSION=1
J519_PKT_STOP=2
PKT_STOP_DATA=struct.pack('>2I', J519_PKT_STOP, J519_VERSION)

parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('HOST', help='Hostname or IP address of controller')
parser.add_argument('PORT', nargs='?',
    help='UDP port to send pkts to',
    default=J519_DEFAULT_PORT)
args = parser.parse_args()

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.sendto(PKT_STOP_DATA, (args.HOST, args.PORT))

print ('Sent DATA STOP packet to udp://{}:{}\n'.format(args.HOST, args.PORT))

time.sleep(0.5)
